name: CI

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  go:
    name: Go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: actions/setup-go@v7.0.0
        with:
          go-version-file: go.mod
      - name: Download dependencies
        run: go mod download
      - name: Test
        run: go test ./...
      - name: Build
        run: go build ./...
